### ISSUE TITLE
HACS Card

### ISSUE THREAD

**Issue by sga-noud** [Dodoooh/awesome-mushroom-cards#4]
# Misc

### HACS Card

Author: [ArenaCloser](https://community.home-assistant.io/u/ArenaCloser) | [HA Community](https://community.home-assistant.io/t/mushroom-cards-build-a-beautiful-dashboard-easily/388590/4125)

![](https://community-assets.home-assistant.io/original/4X/c/4/0/c40d04e4f5e3325d50540673be29e64cb2344f9f.jpeg)

**Entities:**
* sensor.hacs `Required`

```
type: custom:mushroom-template-card
entity: ''
icon: mdi:store
icon_color: |-
  {% if states('sensor.hacs') == "0" %}
  green
  {% else %}
  orange
  {% endif %}
primary: HACS
secondary: |-
  {% if states('sensor.hacs') == "0" %}
  Up-to-date
  {% else %}
  {% for item in state_attr('sensor.hacs', 'repositories') -%}
    {%- if loop.first %}{{states('sensor.hacs')}} update(s): {% elif loop.last %} en {% else %}, {% endif -%}
    '{{ item.display_name | lower }}'
  {%- endfor %}
  {% endif %}
multiline_secondary: true
fill_container: false
tap_action:
  action: navigate
  navigation_path: ../hacs/entry
```

**Comment by Dodoooh** [comment]
thank you, has been added: https://dodoooh.github.io/awesome-mushroom-cards/#/mushroom-cards/monitoring/monitoring-01?id=hacs-card
